.TH "pgo-load " "1" " Container Image Pages" "Jeff McCormick" "August 17, 2018"
.nh
.ad l


.SH NAME
.PP
pgo-backrest \- performs pgbackrest commands on a container


.SH DESCRIPTION
.PP
Works in conjunction with Crunchy Data's PostgreSQL Operator to execute pgbackrest commands on a database

.PP
The container itself consists of:
    \- RHEL7 base image
    \- Bash script that performs the container startup

.PP
Files added to the container during Docker build include: /help.1.


.SH USAGE
.PP
For more information on the PostgreSQL Operator, see the official Crunchy Postgres Operator repository on GitHub.


.SH LABELS
.PP
The starter container includes the following LABEL settings:

.PP
That atomic command runs the Docker command set in this label:

.PP
\fB\fCName=\fR

.PP
The registry location and name of the image. For example, Name="crunchydata/pgo-load".

.PP
\fB\fCVersion=\fR

.PP
The Red Hat Enterprise Linux version from which the container was built. For example, Version="7.5"

.PP
\fB\fCRelease=\fR

.PP
The specific release number of the container. For example, Release="3.2.0"
