# operator

=== Project Structure and Dependencies
....
mkdir -p $HOME/odev/src $HOME/odev/bin $HOME/odev/pkg
export GOPATH=$HOME/odev
export GOBIN=$GOPATH/bin
mkdir -p $GOPATH/github.com/crunchydata/
cd $GOPATH/github.com/crunchydata
git clone https://github.com/CrunchyData/operator.git
cd operator
go get -u github.com/FiloSottile/gvt
....

=== Test Environment

minikube 1.6.0-alpha, executed using:
....
minikube start --kubernetes-version=v1.6.0-alpha.0 --feature-gates=AllAlpha=true
....

=== Allowing minikube Docker Image Access

On minikube, to use the local docker image, in /etc/sysconfig/docker:
....
< DOCKER_CERT_PATH=/etc/docker
---
> if [ -z "${DOCKER_CERT_PATH}" ]; then
>   DOCKER_CERT_PATH=/etc/docker
> fi
....

then,
....
eval $(minikube docker-env)
....

=== Building
....
gvt restore
make operatorserver
....

Current dependencies include:
....
gvt fetch -tag v2.0.0 k8s.io/client-go
....

=== CLI 

Only ideas right now:
....
crunchy create database -name=foodb
crunchy create database -name=foodb -pvc=foopvc
crunchy create cluster -name=mycluster
crunchy create cluster -name=mycluster -pvc=mypvc
crunchy backup -name=foodb -pvc=foopvc
crunchy restore -name=restoredb -pvc=foopvc -archive=foodb-backups/01-09-01-2 -pvc=restorepvc
crunchy show database -name=foodb
crunchy show cluster -name=mycluster
crunchy show cluster -all
crunchy delete cluster -name=mycluster
crunchy delete database -name=foodb
....

Future ideas:
....
crunchy upgrade database -name=foodb -to=9.6
crunchy database policy update -config=pg_hba.conf -name=foodb
crunchy database policy update -config=pg_hba.conf -all
crunchy user add -name=foodb -config=userconfig
crunchy user delete -name=foodb -user=foouser
....
