ARG PREFIX
ARG BASEVER
FROM ${PREFIX}/pgo-base:ubi7-${BASEVER}

LABEL name="pgo-rmdata" \
    run='docker run -d -p 8080:80 --name=web-app web-app' \
    summary="Crunchy Data PostgreSQL Operator - Remove Data" \
    description="Crunchy Data PostgreSQL Operator - Remove Data"

COPY redhat/atomic/pgo_rmdata/help.1 /help.1
COPY redhat/atomic/pgo_rmdata/help.md /help.md

ADD bin/pgo-rmdata/ /usr/local/bin

USER 0

CMD ["/usr/local/bin/start.sh"]
