ARG PREFIX
ARG BASEVER
FROM ${PREFIX}/pgo-base:ubi7-${BASEVER}

LABEL name="pgo-rmdata" \
    summary="Crunchy PostgreSQL Operator - Remove Data" \
    description="Crunchy PostgreSQL Operator - Remove Data"

ADD bin/pgo-rmdata/ /usr/local/bin

USER 0

CMD ["/usr/local/bin/start.sh"]
