ARG PREFIX
ARG BASEVER
FROM ${PREFIX}/pgo-base:ubi7-${BASEVER}

LABEL name="pgo-lspvc" \
    run='docker run -d -p 8080:80 --name=web-app web-app' \
    summary="Crunchy Data PostgreSQL Operator - Display PVC" \
    description="Crunchy Data PostgreSQL Operator - Display contents of a PVC"

COPY redhat/atomic/pgo_lspvc/help.1 /help.1
COPY redhat/atomic/pgo_lspvc/help.md /help.md

USER 26

VOLUME ["/pgdata"]

CMD ["sh", "-c", "find /pgdata/${BACKUP_ROOT}"]
