FROM registry.access.redhat.com/rhel7.3

LABEL Release="1.4" Vendor="Crunchy Data Solutions" 

RUN yum -y update && yum -y clean all


VOLUME ["/pgdata"]

USER 26

CMD ["sh", "-c", "ls /pgdata/${BACKUP_ROOT}"]
