FROM registry.access.redhat.com/rhel7

LABEL Release="3.1" Vendor="Crunchy Data Solutions" 

RUN yum -y update && yum -y clean all


VOLUME ["/pgdata"]

USER 26

CMD ["sh", "-c", "ls /pgdata/${BACKUP_ROOT}"]
