ARG PREFIX
ARG BASEVER
FROM ${PREFIX}/pgo-base:rhel7-${BASEVER}

LABEL name="pgo-event" \
    run='docker run -d -p 8080:80 --name=web-app web-app' \
    summary="Crunchy Data PostgreSQL Operator - pgo-event" \
    description="Crunchy Data PostgreSQL Operator - pgo-event"

ENV PGVERSION="12"

RUN yum -y update && yum -y clean all

ADD bin/pgo-event /usr/local/bin

USER daemon

ENTRYPOINT ["/usr/local/bin/pgo-event.sh"]
