FROM registry.access.redhat.com/rhel7.4

LABEL Release="3.0" Vendor="Crunchy Data Solutions" 

RUN yum -y update && yum -y clean all

VOLUME ["/pgdata"]

USER 26

CMD ["sh", "-xc", "rm -rf /pgdata/${DATA_ROOT}"]
