ARG PREFIX
ARG BASEVER
FROM ${PREFIX}/pgo-base:rhel7-${BASEVER}

LABEL name="pgo-apiserver" \
	summary="Crunchy PostgreSQL Operator - Apiserver" \
	description="Crunchy PostgreSQL Operator - Apiserver"

ENV PGVERSION="12"

RUN yum -y install postgresql${PGVERSION} hostname \
	&& yum -y clean all

ADD bin/apiserver /usr/local/bin
ADD conf/postgres-operator /default-pgo-config

USER daemon

ENTRYPOINT ["/usr/local/bin/apiserver"]
