ARG BASEOS
ARG BASEVER
ARG PREFIX
FROM ${PREFIX}/pgo-base:${BASEOS}-${BASEVER}

LABEL name="pgo-scheduler" \
	summary="Crunchy PostgreSQL Operator - Scheduler" \
	description="Crunchy PostgreSQL Operator - Scheduler"

RUN mkdir -p /opt/cpm/bin /opt/cpm/conf /pgo-config \
 && chown -R 2:2 /opt/cpm /pgo-config

ADD bin/pgo-scheduler /opt/cpm/bin
ADD conf/postgres-operator /default-pgo-config

USER 2

CMD ["/opt/cpm/bin/start.sh"]
