// Copyright 2024 - 2025 Crunchy Data Solutions, Inc.
//
// SPDX-License-Identifier: Apache-2.0

package collector

import (
	"context"
	"testing"

	"gotest.tools/v3/assert"

	"github.com/crunchydata/postgres-operator/internal/feature"
	"github.com/crunchydata/postgres-operator/internal/testing/require"
	"github.com/crunchydata/postgres-operator/pkg/apis/postgres-operator.crunchydata.com/v1beta1"
)

func TestEnablePgBouncerLogging(t *testing.T) {
	t.Run("NilInstrumentationSpec", func(t *testing.T) {
		gate := feature.NewGate()
		assert.NilError(t, gate.SetFromMap(map[string]bool{
			feature.OpenTelemetryLogs: true,
		}))
		ctx := feature.NewContext(context.Background(), gate)

		config := NewConfig(nil)
		cluster := new(v1beta1.PostgresCluster)
		require.UnmarshalInto(t, &cluster.Spec, `{
			instrumentation: {
				logs: { retentionPeriod: 5h },
			},
		}`)
		EnablePgBouncerLogging(ctx, cluster, config)

		result, err := config.ToYAML()
		assert.NilError(t, err)
		assert.DeepEqual(t, result, `# Generated by postgres-operator. DO NOT EDIT.
# Your changes will not be saved.
exporters:
  debug:
    verbosity: detailed
extensions:
  file_storage/pgbouncer_logs:
    create_directory: false
    directory: /tmp/receiver
    fsync: true
processors:
  batch/1s:
    timeout: 1s
  batch/200ms:
    timeout: 200ms
  batch/logs:
    send_batch_size: 8192
    timeout: 200ms
  groupbyattrs/compact: {}
  resource/pgbouncer:
    attributes:
    - action: insert
      key: k8s.container.name
      value: pgbouncer
    - action: insert
      key: k8s.namespace.name
      value: ${env:K8S_POD_NAMESPACE}
    - action: insert
      key: k8s.pod.name
      value: ${env:K8S_POD_NAME}
  resourcedetection:
    detectors: []
    override: false
    timeout: 30s
  transform/pgbouncer_logs:
    log_statements:
    - context: log
      statements:
      - set(instrumentation_scope.name, "pgbouncer")
      - merge_maps(log.cache, ExtractPatterns(log.body, "^(?<timestamp>\\d{4}-\\d{2}-\\d{2}
        \\d{2}:\\d{2}:\\d{2}\\.\\d{3} [A-Z]{3}) \\[(?<pid>\\d+)\\] (?<log_level>[A-Z]+)
        (?<msg>.*$)"), "insert")
      - set(log.severity_text, log.cache["log_level"])
      - set(log.severity_number, SEVERITY_NUMBER_DEBUG)  where log.severity_text ==
        "NOISE" or log.severity_text == "DEBUG"
      - set(log.severity_number, SEVERITY_NUMBER_INFO)   where log.severity_text ==
        "LOG"
      - set(log.severity_number, SEVERITY_NUMBER_WARN)   where log.severity_text ==
        "WARNING"
      - set(log.severity_number, SEVERITY_NUMBER_ERROR)  where log.severity_text ==
        "ERROR"
      - set(log.severity_number, SEVERITY_NUMBER_FATAL)  where log.severity_text ==
        "FATAL"
      - set(log.time, Time(log.cache["timestamp"], "%F %T.%L %Z")) where IsString(log.cache["timestamp"])
      - set(log.attributes["log.record.original"], log.body)
      - set(log.attributes["process.pid"], log.cache["pid"])
      - set(log.body, log.cache["msg"])
receivers:
  filelog/pgbouncer_log:
    include:
    - /tmp/*.log
    - /tmp/*.log.1
    storage: file_storage/pgbouncer_logs
service:
  extensions:
  - file_storage/pgbouncer_logs
  pipelines:
    logs/pgbouncer:
      exporters:
      - debug
      processors:
      - resource/pgbouncer
      - transform/pgbouncer_logs
      - resourcedetection
      - batch/logs
      - groupbyattrs/compact
      receivers:
      - filelog/pgbouncer_log
`)
	})

	t.Run("InstrumentationSpecDefined", func(t *testing.T) {
		gate := feature.NewGate()
		assert.NilError(t, gate.SetFromMap(map[string]bool{
			feature.OpenTelemetryLogs: true,
		}))
		ctx := feature.NewContext(context.Background(), gate)

		config := NewConfig(testInstrumentationSpec())

		cluster := new(v1beta1.PostgresCluster)
		cluster.Spec.Instrumentation = testInstrumentationSpec()

		EnablePgBouncerLogging(ctx, cluster, config)

		result, err := config.ToYAML()
		assert.NilError(t, err)
		assert.DeepEqual(t, result, `# Generated by postgres-operator. DO NOT EDIT.
# Your changes will not be saved.
exporters:
  debug:
    verbosity: detailed
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
    project: google-project-name
extensions:
  file_storage/pgbouncer_logs:
    create_directory: false
    directory: /tmp/receiver
    fsync: true
processors:
  batch/1s:
    timeout: 1s
  batch/200ms:
    timeout: 200ms
  batch/logs:
    send_batch_size: 8192
    timeout: 200ms
  groupbyattrs/compact: {}
  resource/pgbouncer:
    attributes:
    - action: insert
      key: k8s.container.name
      value: pgbouncer
    - action: insert
      key: k8s.namespace.name
      value: ${env:K8S_POD_NAMESPACE}
    - action: insert
      key: k8s.pod.name
      value: ${env:K8S_POD_NAME}
  resourcedetection:
    detectors: []
    override: false
    timeout: 30s
  transform/pgbouncer_logs:
    log_statements:
    - context: log
      statements:
      - set(instrumentation_scope.name, "pgbouncer")
      - merge_maps(log.cache, ExtractPatterns(log.body, "^(?<timestamp>\\d{4}-\\d{2}-\\d{2}
        \\d{2}:\\d{2}:\\d{2}\\.\\d{3} [A-Z]{3}) \\[(?<pid>\\d+)\\] (?<log_level>[A-Z]+)
        (?<msg>.*$)"), "insert")
      - set(log.severity_text, log.cache["log_level"])
      - set(log.severity_number, SEVERITY_NUMBER_DEBUG)  where log.severity_text ==
        "NOISE" or log.severity_text == "DEBUG"
      - set(log.severity_number, SEVERITY_NUMBER_INFO)   where log.severity_text ==
        "LOG"
      - set(log.severity_number, SEVERITY_NUMBER_WARN)   where log.severity_text ==
        "WARNING"
      - set(log.severity_number, SEVERITY_NUMBER_ERROR)  where log.severity_text ==
        "ERROR"
      - set(log.severity_number, SEVERITY_NUMBER_FATAL)  where log.severity_text ==
        "FATAL"
      - set(log.time, Time(log.cache["timestamp"], "%F %T.%L %Z")) where IsString(log.cache["timestamp"])
      - set(log.attributes["log.record.original"], log.body)
      - set(log.attributes["process.pid"], log.cache["pid"])
      - set(log.body, log.cache["msg"])
receivers:
  filelog/pgbouncer_log:
    include:
    - /tmp/*.log
    - /tmp/*.log.1
    storage: file_storage/pgbouncer_logs
service:
  extensions:
  - file_storage/pgbouncer_logs
  pipelines:
    logs/pgbouncer:
      exporters:
      - googlecloud
      processors:
      - resource/pgbouncer
      - transform/pgbouncer_logs
      - resourcedetection
      - batch/logs
      - groupbyattrs/compact
      receivers:
      - filelog/pgbouncer_log
`)
	})
}
