---
title: "Installation"
date: 2018-04-24T18:27:02-07:00
draft: false
weight: 10
---

Latest Release: 3.2.0 {docdate}

== Installation

For a quick deployment on either a GKE or OpenShift environment, visit the
link:/installation/quick-installation/[Quick Installation] page.

For a manual installation of the Operator on either a Kubernetes or OpenShift
environment, visit the link:/installation/manual-installation/[Manual Installation]
page.

A link:/installation/helm-chart/[Helm Chart] is also provided.

If you're looking to upgrade a current PostgreSQL Operator installation, visit the
link:/installation/upgrading-the-operator/[Upgrading the Operator] page.

There are many ways to configure the operator further. Some sample configurations are
documented on the link:/installation/configuration/[Configuration] page. This includes
setting up security and storage configurations for your environment.

After completing the installation steps, ensure you visit the
link:/installation/deployment/[Deployment] page to deploy the Operator to your
environment.

== Next Steps

You may want to find out more information on how the operator is designed to work and
deploy. This information can be found in the link:/how-it-works/[How It Works] page.

Information can be found on the full scope of commands on the
link:/getting-started/[Getting Started] page.
