---
title: "Deployment"
date: 2018-04-26T15:26:40-07:00
draft: false
weight: 50
---

:toc:
v2.6, {docdate}

This document details verifying the installation of the PostgreSQL Operator
is successful, in addition to detailing some different storage configurations
that can be made.

== Verify Operator Status

To verify that the operator is deployed and running, run the following:
....
kubectl get pod --selector=name=postgres-operator
....

You should see output similar to this:
....
NAME                                 READY     STATUS    RESTARTS   AGE
postgres-operator-56598999cd-tbg4w   2/2       Running   0          1m
....

There are 2 containers in the operator pod, both should be *ready* as above.

When you first run the operator, it will create the required
CustomResourceDefinitions. You can view these as follows -
....
kubectl get crd
....

The operator creates the following Custom Resource Definitions over time as the
associated commands are triggered.
....
kubectl get crd
NAME                             AGE
pgbackups.cr.client-go.k8s.io    2d
pgclusters.cr.client-go.k8s.io   2d
pgingests.cr.client-go.k8s.io    2d
pgpolicies.cr.client-go.k8s.io   2d
pgreplicas.cr.client-go.k8s.io   2d
pgtasks.cr.client-go.k8s.io      2d
pgupgrades.cr.client-go.k8s.io   2d
....

At this point, the server side of the operator is deployed and ready.

The complete set of environment variables used in the installation
so far are -
....
export CO_IMAGE_PREFIX=crunchydata
export CO_IMAGE_TAG=centos7-2.6
export GOPATH=$HOME/odev
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
export COROOT=$GOPATH/src/github.com/crunchydata/postgres-operator
export CO_CMD=kubectl
....

You would normally add these into your *.bashrc* at this point to be used later on or if you want to redeploy the operator.

== Configure *pgo* Client

The pgo command line client requires TLS for securing the connection to the operator's REST API.  This configuration is performed as follows -
....
export PGO_CA_CERT=$COROOT/conf/apiserver/server.crt
export PGO_CLIENT_CERT=$COROOT/conf/apiserver/server.crt
export PGO_CLIENT_KEY=$COROOT/conf/apiserver/server.key
....

The pgo client uses Basic Authentication to authenticate to the operator REST API, for authentication, add the following `.pgouser` file to your $HOME -
....
echo "username:password" > $HOME/.pgouser
....

The *pgo* client needs the URL to connect to the operator.

Depending on your Kubernetes environment this can be done the following ways.

{{%expand "Running Kubernetes Locally" %}}

=== Running Kubernetes Locally

If your local host is not set up to resolve Kubernetes Service DNS names, you can specify the operator IP address as follows -
....
kubectl get service postgres-operator
NAME                TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
postgres-operator   NodePort   10.109.184.8   <none>        8443:30894/TCP   5m

export CO_APISERVER_URL=https://10.109.184.8:8443
pgo version
....

It is also possible to define a bash alias such as -
....
alias setip='export CO_APISERVER_URL=https://`kubectl get service postgres-operator -o=jsonpath="{.spec.clusterIP}"`:8443'
....

This alias will set the `CO_APISERVER_URL` IP address for you.

{{% /expand%}}

{{%expand "Running Kubernetes Remotely" %}}

==== Running Kubernetes Remotely

Set up a port-forward tunnel from your host to the Kube remote host, specifying the operator pod -
....
kubectl get pod --selector=name=postgres-operator
NAME                                 READY     STATUS    RESTARTS   AGE
postgres-operator-56598999cd-tbg4w   2/2       Running   0          8m

kubectl port-forward postgres-operator-56598999cd-tbg4w 8443:8443
....

In another terminal -
....
export CO_APISERVER_URL=https://127.0.0.1:8443
pgo version
....

{{% /expand%}}

== Verify pgo Client

At this point you should be able to connect to the operator as follows -
....
pgo version
pgo client version 2.6
apiserver version 2.6
....

Operator commands are documented on the link:/getting-started/[Getting Started] page.

== Storage Configuration

Most users after they try out the operator will want to create a more customized installation and deployment of the operator using specific storage types.

The operator will work with HostPath, NFS, Dynamic, and GKE Storage.

{{%expand "NFS" %}}

=== NFS

To configure the operator to use NFS for storage, a sample *pgo.yaml.nfs* file is provided.  Overlay the default `pgo.yaml` file with that file -
....
cp $COROOT/examples/pgo.yaml.nfs $COROOT/conf/apiserver/pgo.yaml
....

Edit the *pgo.yaml* file to specify the NFS GID that is set for the NFS volume mount you will be using, the default value assumed is *nfsnobody* as the GID (65534).  Update the value to meet your NFS security settings.

There is currently no script available to create your NFS Persistent Volumes but you can typically modify the `$COROOT/pv/create-pv.sh` script to work with NFS.

{{% /expand%}}

{{%expand "Dynamic" %}}

=== Dynamic

To configure the operator to use Dynamic Storage classes for storage, a sample *pgo.yaml.storageclass* file is provided.  Overlay the default *pgo.yaml* file with that file -
....
cp $COROOT/examples/pgo.yaml.storageclass $COROOT/conf/apiserver/pgo.yaml
....

Edit the *pgo.yaml* file to specify the storage class you will be using, the default value assumed is *standard* which is the name used by default within a GKE Kube cluster deployment.  Update the value to match your storage classes.

Notice that the *FsGroup* setting is required for most block storage and is set to the value of *26* since the PostgreSQL container runs as UID *26*.

{{% /expand%}}

{{%expand "GKE" %}}

=== GKE

Some notes for setting up GKE for the Operator deployment.

==== Install Kubectl

On your host you will be working from, install the kubectl command -

https://kubernetes.io/docs/tasks/tools/install-kubectl/

==== GCP

* Select your project
* Create a Kube cluster in that project

By default a storage class called *standard* is created.

==== Install GCloud

To access the Kubernetes cluster, install the gcloud utility -

....
https://cloud.google.com/sdk/downloads
cd google-cloud-sdk
./install.sh
....

==== Configure Kubectl for Cluster Access

....
gcloud auth login

gcloud container clusters get-credentials jeff-quickstart --zone us-central1-a --project crunchy-dev-test

kubectl get storageclass
....

{{% /expand%}}

== Next Steps

There are many ways to configure the operator further. Some sample configurations are
documented on the link:/installation/configuration/[Configuration] page.

You may also want to find out more information on how the operator is designed to work and
deploy. This information can be found in the link:/how-it-works/[How It Works] page.

Information can be found on the full scope of commands on the
link:/getting-started/[Getting Started] page.
