---
title: "Manual Installation"
date: 2018-04-26T15:22:21-07:00
draft: false
weight: 20
---

:toc:
Latest Release: 3.4.0 {docdate}

== Project Structure

First, define the following environment variables in *.bashrc*:
....
export GOPATH=$HOME/odev
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
export CO_NAMESPACE=demo
export CO_CMD=kubectl
export COROOT=$GOPATH/src/github.com/crunchydata/postgres-operator
export CO_IMAGE_PREFIX=crunchydata
export CO_BASEOS=centos7
export CO_VERSION=3.4.0
export CO_IMAGE_TAG=$CO_BASEOS-$CO_VERSION

# for the pgo CLI auth
export PGO_CA_CERT=$COROOT/conf/postgres-operator/server.crt
export PGO_CLIENT_CERT=$COROOT/conf/postgres-operator/server.crt
export PGO_CLIENT_KEY=$COROOT/conf/postgres-operator/server.key

# for crunchy-scheduler startup
export CCP_IMAGE_PREFIX=crunchydata
export CCP_IMAGE_TAG=centos7-10.5-2.2.0

# useful aliases
alias setip='export CO_APISERVER_URL=https://`kubectl get service postgres-operator -o=jsonpath="{.spec.clusterIP}"`:8443'
alias alog='kubectl logs `kubectl get pod --selector=name=postgres-operator -o jsonpath="{.items[0].metadata.name}"` -c apiserver'
alias olog='kubectl logs `kubectl get pod --selector=name=postgres-operator -o jsonpath="{.items[0].metadata.name}"` -c operator'
....

If you have access to the Crunchy RHEL images, you would change
the above references to centos7 to rhel7.

When deploying on Openshift Container Platform, the CO_CMD environment
variable should be:
....
export CO_CMD=oc
....

To perform an installation of the operator, first create the project structure as follows on your host, here we assume a local directory called *odev* -
....
. .bashrc
mkdir -p $HOME/odev/src $HOME/odev/bin $HOME/odev/pkg $GOPATH/src/github.com/crunchydata/
....

Next, get a tagged release of the source code -
....
cd $GOPATH/src/github.com/crunchydata
git clone https://github.com/CrunchyData/postgres-operator.git
cd postgres-operator
git checkout 3.4.0
....

== Installation Prerequsites

To run the operator and the *pgo* client, you will need the following -

 * a running Kubernetes or OpenShift cluster
 * the kubectl or oc clients installed in your PATH and configured to connect to the cluster (e.g. export KUBECONFIG=/etc/kubernetes/admin.conf)
 * a Kubernetes namespace created and set to where you want the operator installed. For this install we assume a namespace of *demo* has been created.
....
kubectl create -f examples/demo-namespace.json
kubectl config set-context $(kubectl config current-context) --namespace=demo
kubectl config view -o "jsonpath={.contexts[?(@.name==\"$(kubectl config current-context 2>/dev/null)\")].context.namespace}"
....

On Openshift Container Platform, you would have a Project and User defined
for installing the Operator.  

Run the Makefile `setup` target to install depedencies.
....
make setup
....

Next, run the Makefile `installrbac` target as a user with cluster-admin
priviledges, not as a normal Kube or Openshift user.  This target creates the RBAC
roles and CRDs required by the Operator and is only required to be created
one time.

For example, on an Openshift system you would run this target as
follows using the system:admin Openshift user:
....
$ sudo su -
# oc login -u system:admin
# cd /home/oper
# . .bashrc
# export PATH=$PATH:/home/oper/odev/bin
# cd odev/src/github.com/crunchydata/postgres-operator
# make installrbac
....

On a Kube system, you would be connected as a cluster-admin user
and just issue:
....
# cd /home/oper
# . .bashrc
# export PATH=$PATH:/home/oper/odev/bin
# cd odev/src/github.com/crunchydata/postgres-operator
make installrbac
....


== Basic Installation

The basic pgo.yaml configuration specifies 3 different
storage configurations:
 * hostpath 
 * nfs (default)
 * storage-class 

Storage configurations are documented here:
link:/installation/configuration/#_storage_configuration[here].

The default storage configuration used for creating Primary, Replica, and
Backups is set to NFS in the default pgo.yaml file.  Adjust this setting
to meet your storage requirements.

Sample PV creation scripts are found in the following directory:
....
examples/pv
....

=== HostPath Persistent Volumes

The default Persistent Volume script assumes a default HostPath directory be created called */data*:
....
sudo mkdir /data
sudo chmod 777 /data
....

Create some sample Persistent Volumes using the following script:
....
$COROOT/pv/create-pv.sh
....

=== NFS Persistent Volumes

The NFS Persistent Volume script assumes a default directory be created called */nfsfileshare* as the NFS mount point on your system:
....
sudo ls /nfsfileshare
....

See the crunchy-containers documentation on how to install NFS on a
centos/RHEL system if you want to use NFS for testing the operator.

Create some sample NFS Persistent Volumes using the following script:
....
$COROOT/pv/create-nfs-pv.sh
....

== Build Images & Deploy

{{%expand "Packaged Images" %}}

=== Packaged Images

To pull prebuilt versions from Dockerhub of the *postgres-operator* containers, execute the following Makefile target -
....
make pull
....

To pull down the prebuilt *pgo* binaries, download the *tar.gz* release file from the following link -

 * link:https://github.com/CrunchyData/postgres-operator/releases[Github Releases]
 * extract (e.g. tar xvzf postgres-operator.3.4.0.tar.gz)
....
cd $HOME
tar xvzf ./postgres-operator.3.4.0.tar.gz
....
 * copy *pgo* client to somewhere in your path (e.g. cp pgo /usr/local/bin)

Next, deploy the operator to your Kubernetes cluster -
....
cd $COROOT
make deployoperator
....

[WARNING]
====
If you make configuration file changes you will need to re-run the
`deployoperator` makefile target to re-deploy the Operator with the
new configuration files.
====

{{% /expand%}}

{{%expand "Build from Source" %}}

=== Build from Source

The purpose of this section is to illustrate how to build the PostgreSQL
Operator from source. These are considered advanced installation steps and
should be primarily used by developers or those wishing a more precise
installation method.

==== Requirements

The postgres-operator runs on any Kubernetes and Openshift platform that supports
Custom Resource Definitions. The Operator is tested on Kubeadm and OpenShift
Container Platform environments.

The operator is developed with the Golang versions greater than or equal to version 1.8. See
link:https://golang.org/dl/[Golang website] for details on installing golang.

The Operator project builds and operates with the following containers -

* link:https://hub.docker.com/r/crunchydata/pgo-lspvc/[PVC Listing Container]
* link:https://hub.docker.com/r/crunchydata/pgo-rmdata/[Remove Data Container]
* link:https://hub.docker.com/r/crunchydata/postgres-operator/[postgres-operator Container]
* link:https://hub.docker.com/r/crunchydata/pgo-apiserver/[apiserver Container]
* link:https://hub.docker.com/r/crunchydata/pgo-load/[file load Container]
* link:https://hub.docker.com/r/crunchydata/pgo-backrest/[pgbackrest interface Container]

This Operator is developed and tested on the following operating systems but is known to run on other operating systems -

* *CentOS 7*
* *RHEL 7*

{{% /expand%}}

== Makefile Targets

The following table describes the Makefile targets -

.Makefile Targets
[width="80%",frame="topbot",options="header"]
|======================
|Target | Description
|macpgo      | build the Mac version of the pgo CLI binary
|winpgo      | build the Windows version of the pgo CLI binary
|installrbac | only run once and by a cluster-admin user, this target creates the Operator CRDs and RBAC resources required by the Operator
|setupnamespace | only run once, will create a namespace called *demo*
|bounce        | delete the Operator pod only, this is a way to upgrade the operator without a full redeploy, as the operator runs in a Deployment, a new pod will be created to replace the old one, a simple way to bounce the pod
|deployoperator        | deploy the Operator (apiserver and postgers-operator) to Kubernetes
|all        | compile all binaries and build all images
|setup        | fetch the dependent packages required to build with, and create Kube RBAC resources
|main        | compile the postgres-operator
|pgo        | build the pgo binary
|clean        | remove binaries and compiled packages, restore dependencies
|operatorimage        | compile and build the postgres-operator Docker image
|apiserverimage        | compile and build the apiserver Docker image
|lsimage        | build the lspvc Docker image
|loadimage        | build the file load Docker image
|rmdataimage        | build the data deletion Docker image
|pgo-backrest-image        | build the pgbackrest interface Docker image
|release        | build the postgres-operator release
|======================

== Next Steps

Next, visit the link:/installation/deployment/[Deployment] page to deploy the
Operator, verify the installation, and view various storage configurations.
