---
title: "Quick Installation"
date: 2018-04-26T15:22:14-07:00
draft: false
weight: 10
---

:toc:
Latest Release: 3.2.0 {docdate}

== Overview

There are currently *quickstart* scripts that seek to automate
the deployment to popular Kubernetes environments -

 * link:https://github.com/CrunchyData/postgres-operator/blob/master/examples/quickstart-for-gke.sh[quickstart-for-gke.sh]
 * link:https://github.com/CrunchyData/postgres-operator/blob/master/examples/quickstart-for-ocp.sh[quickstart-for-ocp.sh]

The *quickstart-for-gke* script will deploy the operator to
a GKE Kube cluster.

The *quickstart-for-ocp* script will deploy the operator to
an Openshift Container Platform cluster.

Both scripts assume you have a StorageClass defined for persistence.

Pre-compiled versions of the Operator *pgo* client are provided for the x86_64, Mac OSX, and Windows hosts.

== Quickstart

=== GKE/PKS
The *quickstart-for-gke.sh* script will allow users to set up the Postgres Operator quickly on GKE including PKS.
This script is tested on GKE but can be modified for use with other Kubernetes environments as well.

The script requires a few things in order to work -

 * wget utility installed
 * kubectl utility installed
 * StorageClass defined on your GKE instance

Executing the script will give you a default Operator deployment
that assumes *dynamic* storage and a storage class named *standard*,
things that GKE provides.

The script performs the following -

 * downloads the Operator configuration files
 * sets the $HOME/.pgouser file to default settings
 * deploys the Operator Deployment
 * sets your .bashrc to include the Operator environment variables
 * sets your $HOME/.bash_completion file to be the *pgo* bash_completion file

A tip, if you want to set your Kube context to some particular namespace you 
can run commands similar to this to set it to a *demo* namespace if
that namespace has already been created on your GKE cluster:
....
kubectl create -f $COROOT/examples/demo-namespace.json
kubectl config set-context demo --cluster=gke_crunchy-a-test_us-central1-a_usera-quickstart --namespace=demo --user=gke_crunchy-a-test_us-central1-a_usera-quickstart
kubectl config use-context demo
....

For Mac and Windows users, pre-built *pgo* binaries are included in
the operator release tar ball:

 * pgo-mac is the Mac binary
 * pgo.exe is the Windows binary
 * pgo is the Linux binary
 * expenv-mac is the expenv binary for Mac
 * expenv.exe is the expenv binary for Windows

Currently the quickstart scripts are meant for Linux installs, you will
need to modify this script for Windows or Mac installs until we support
and provide Windows and Mac installation scripts.

=== Openshift Container Platform

A similar script for installing the operator on OCP is
offered with similar features as the GKE script.  This script is
tested on OCP 3.7 with a StorageClass defined.

== Next Steps

Next, visit the link:/installation/deployment/[Deployment] page to deploy the
Operator, verify the installation, and view various storage configurations.
