---
title: "Upgrading the Operator"
date: 2018-04-24T18:27:30-07:00
draft: false
weight: 60
---

Latest Release: 3.4.0 {docdate}

{{% expand "Upgrading to v3.4" %}}

 * The conf/apiserver/ configuration files were moved into the 
conf/postgres-operator directory to consolidate all config
files into a single location.  You will need to perform
this step manually start with version 3.4.0 if you are running
an existing Operator version prior to 3.4.0.  The Helm chart
is also updated to reflect this change.  Starting with 3.4.0
there is a secret, *pgo-auth-secret* that holds authentication and
authorization files used by the operator to authenticate REST
clients.  Also, the configuration files are stored in a configmap
named *pgo-config*.  Existing users will need to update
their deploy.sh script and deployment.yaml files to pick up the
the new naming conventions.
 * new configuration settings were added into pgo.yaml to support
resource configuration settings for the various *helper* containers.
The new settings include DefaultLoadResources, DefaultLspvcResources,
DefaultRmdataResources, DefaultBackupResources.  You will need to add
these manually into your existing pgo.yaml file if you want to
make use of this feature.
 * the pgcluster CRD was changed to remove the password fields, instead
secret names are stored in the CRD to avoid having to have passwords
in the CRD, the password fields are totally removed starting in this
release. No changes are required for existing CRD resources, new
CRDs that are created will not have the  password fields.
 * starting in 3.4, a new operator upgrade process is developed that
eventually will handle various forms of automated upgrades depending
on user settings and changes to the postgres-operator in between
versions.  When starting a new Operator it will scan the pgcluster
and pgreplica instances and update the pgo-version to match the
current operator version, it will also create a user label on 
the pgreplica/pgcluster to indicate the upgrade date.  More advanced
upgrade features are planned to be developed.
 * in 3.4, the pgo.yaml LogStatement and LogMinDurationStatement settings
are present, if not set, defaults are supplied for both.  These settings
let you define more precisely the degree of Postgres logging for 
any Postgres clusters created by the Operator.  The LogStatement default
is 'none' and the LogMinDurationStatement defaults to 60000 (milliseconds).
These settings greatly reduce the log file sizes and only will log
statements that are longer running that 60000 milliseconds.  If you
want to see all statements logged, set LogStatement to 'all'.
 * in 3.4, the pgbackup CRD includes a new field called BackupOpts, used
to hold the pgbasebackup command options which can now be passed in
on the CLI backup command, no changes to existing pgbackup CRD resources is
required.
* operator 3.3 introduced the alpha version of pgbackrest integration.
Now in 3.4, the pgbackrest integration was changed so that users
no longer have to specify a custom configuration file using *--custom-config*.
* the pgo-backrest backup-job is secured with a new service account
named pgo-backrest, that SA is now included in the rbac.yaml file and is
to be created by an a cluster admin user
* the permission SHOW_WORKFLOW_PERM was created and added to the default pgorole example, this permission lets users view workflow status, workflows are stored as pgtask CRDs

With 3.4, there is a global configmap created as part of the
deployment process which will serve this same purpose, that is to 
indicate to the Postgres container that it must allocate the pgbackrest
directories within the mounted /backrestrepo volume mount.  This
means however, that if you specify a global configuration file or
specify your own custom configuration that you have to include
the pgbackrest.conf file and key within that configmap.  The sample
global custom configuration map, pgo-custom-pg-config, now includes
pgbackrest.conf within it.  

This new integration only works with pgbackrest v2.6 which is included 
into crunchy-postgres 2.2.0.  This means that to use pgbackrest, you 
must run crunchy-postgres 2.2.0 or greater which will require users
to upgrade the pgo.yaml to use the 2.2.0 CCPImageTag.  pgbackrest commands
will NOT work with clusters using older Postgres images.

{{% expand "Upgrading to v3.3" %}}

The following changes are mandatory when upgrading to 3.3 from previous operator versions:

 * The MatchLabels attribute was added to the pgo.yaml file as an optional
   storage configuration setting. You do not have to specify this setting,
   however, the operator-conf ConfigMap now has to include the `pvc-matchlabels.json`
   template file as required by this new feature. If you upgrade to
   3.2, you will need to rebuild your *operator-conf* ConfigMap to include
   `pvc-matchlabels.json` and redeploy the Operator using the new ConfigMap.
 * The `CCP_IMAGE_PREFIX`, `CO_IMAGE_PREFIX`, and `CO_IMAGE_TAG` environment variables are now pulled from the `pgo.yaml` configuration file that is mounted by both the apiserver and operator containers. To clean up an existing deployment, remove these environment variable definitions from your `deployment.yaml` file or Helm chart equivalent.
 * The `ExternalIP` field was added to the `apiservermsgs.ShowClusterService`
   struct. This field is now passed back to apiserver clients in the
   REST API when viewing cluster details. For custom clients you might
   have written, you will see this new field in the REST message.
 * Clusters that were created prior to 3.1 will need a new label to be applied. For primary deployments, apply the label `primary=true`. For example, `kubectl label deploy mycluster primary=true`. For replica deployments, specify `primary=false`. For example,	`kubectl label deploy mycluster-xxxx primary=false`.
 * The `collect.json` template now specifies a pgmonitor credential that
   must match the `PGMONITOR_PASSWORD` environment variable which was
   added into the `cluster-deployment-1.json` template.  These changes
   were required to support crunchy-collect (2.1.0) changes that were
   introduced.  Users should upgrade to `crunchy-collect:centos7-10.5-2.1.0`
   to use this feature.  If you do not want to upgrade to this new
   metrics collector, you will need to retain and reuse the prior version
   of `collect.json` used by the Operator and make sure you deploy that
   version.

{{% /expand %}}

{{% expand "Upgrading from v2.6 to v3.1" %}}

Clusters that were created prior to 3.1 will need a new label to be applied.
For primary deployments, apply the label `primary=true`. For example,
`kubectl label deploy mycluster primary=true`. For replica deployments, specify
`primary=false`. For example,	`kubectl label deploy mycluster-xxxx primary=false`.

{{% /expand %}}

{{% expand "Upgrading from v2.4 to v2.5" %}}

For a full list of additions and revisions that occurred in the
PostgreSQL Operator v2.5 release, please view the related release
page link:https://github.com/CrunchyData/postgres-operator/releases/tag/2.5[here].

== Required Updates

This section notes some required steps that will need to be taken
in the process of upgrading from v2.4 to v2.5.

=== Configuration File

It will be necessary to update your existing `pgo.yaml` configuration
file where the Storage Configuration sections are concerned. The updated
file for v2.5 can be found
link:https://github.com/CrunchyData/postgres-operator/blob/2.5/conf/apiserver/pgo.yaml[here].
The file contained within the local installation of the Operator is located
by default in the following location -
....
$COROOT/conf/apiserver/pgo.yaml
....

=== Secrets

2.5 changed the names of the database credentials that are created
by default in order to be consistent with the way new database credentials
are named.

It will be necessary to run the following script to update your
existing clusters. This script will essentially copy the existing
secrets values and create new secrets with those same values but
named to the new standard. Run the script by passing in the name of
an existing cluster as a parameter.

....
$COROOT/bin/upgrade-secret.sh
....

{{% /expand %}}

{{% expand "Upgrading from v2.5 to v2.6" %}}

For a full list of additions and revisions that occurred in the
PostgreSQL Operator v2.5 release, please view the related release
page link:https://github.com/CrunchyData/postgres-operator/releases/tag/3.3.0[here].

== Required Updates

This section notes some required steps that will need to be taken
in the process of upgrading from v2.5 to v2.6.

=== Configuration File

One update in v2.6 changed the `pgo.yaml` file through removing the Debug flag.
The `Pgo.Debug` variable can now be removed from the `pgo.yaml` file as a
result. The debug flag is now called `CRUNCHY_DEBUG` and is set in the
`deployment.json` file as a default environment variable.

=== Container Resources

Release 2.6 added the concept of container resource configurations
to the `pgo.yaml` file. In order to specify the optional container
resource configurations, add a section as follows to your `pgo.yaml`
file -
....
DefaultContainerResource: small
ContainerResources:
 small:
   RequestsMemory:  2Gi
   RequestsCPU:  0.5
   LimitsMemory:  2Gi
   LimitsCPU:  1.0
 large:
   RequestsMemory:  8Gi
   RequestsCPU:  2.0
   LimitsMemory:  12Gi
   LimitsCPU:  4.0
....

If these settings are set incorrectly or if the Kubernetes cluster
cannot meet the defined memory and CPU requirements, deployments will go into
a *pending* state.

=== Kube RBAC

Release 2.6 added a `rbac.yaml` file to capture the Kube RBAC
rules. These RBAC rules allow the *apiserver* and *postgres-operator*
containers access to the Kubernetes resources required for
the operator to work. As part of the deployment process, it is necessary to
execute the `rbac.yaml` file to set the roles and bindings required by the
operator. Adjust this file to suit local security requirements.

=== Application RBAC

Release 2.6 added an RBAC capability to secure the *pgo* application.
The *pgouser* now has a role appended at the end of of each user definition
as follows -
....
username:password:pgoadmin
testuser:testpass:pgoadmin
readonlyuser:testpass:pgoreader
....

These are defined in the following file -
....
$COROOT/conf/apiserver/pgouser
....

To match the behavior of the pre 2.6 releases, the *pgadmin* role
is set on the previous user definitions, but a *readonlyuser* is
now defined to test other role definitions. The roles are defined in
a new file called *pgorole*. This file defines each role and the
permissions for that role. By default, two roles are defined as samples -
....
pgoadmin
pgoreader
....

Adjust these default settings to meet local security requirements.

The format of this file is as follows -
....
rolename: permissionA, permissionB
....

These are defined in the following file -
....
$COROOT/conf/apiserver/pgorole
....

The complete set of permissions is documented in the link:/installation/configuration/[Configuration] document.

=== User Creation

Release 2.6 replaced the `pgo user --add` command with the `pgo create user`
command to improve consistency across command usage. Any scripts written
using the older style of command require an update to use the new command
syntax.

=== Replica CRD

There is a new Kubernetes Custom Resource Definition that serves the purpose
of holding replica information, called *pgreplicas*. This CRD is populated
with the pgo scale command and is used to hold per-replica specific information
such as the resource and storage configurations requested at run time.

{{% /expand %}}
