---
title: "Contributing"
date: 2018-04-29T13:22:59-07:00
draft: false
weight: 40
---

Latest Release: 3.4.0 {docdate}

== Getting Started

Welcome! Thank you for your interest in contributing. Before submitting a new link:https://github.com/CrunchyData/postgres-operator/issues/new[issue]
or link:https://github.com/CrunchyData/postgres-operator/pulls[pull request] to the link:https://github.com/CrunchyData/postgres-operator/[Crunchy Data
PostgreSQL Operator] project on GitHub, *please review any open or closed issues* link:https://github.com/crunchydata/postgres-operator/issues[here]
in addition to any existing open pull requests.

== Documentation

The documentation website (located at https://crunchydata.github.io/postgres-operator/) is generated using link:https://gohugo.io/[Hugo] and
link:https://pages.github.com/[GitHub Pages].

== Hosting Hugo Locally (Optional)

If you would like to build the documentation locally, view the
link:https://gohugo.io/getting-started/installing/[official Installing Hugo] guide to set up Hugo locally. You can then start the server by
running the following commands -

....
cd $CCPROOT/hugo/
vi config.toml
hugo server
....

The local version of the Hugo server is accessible by default from
`localhost:1313`. Once you've run `hugo server`, that will let you interactively make changes to the documentation as desired and view the updates
in real-time.
