.TH "postgres-operator " "1" " Container Image Pages" "Crunchy Data" "December 23, 2019"
.nh
.ad l


.SH NAME
.PP
postgres-operator \- Trusted open-source PostgreSQL-as-a-Service


.SH DESCRIPTION
.PP
The Crunchy PostgreSQL Operator automates and simplifies deploying and managing open source PostgreSQL clusters on Kubernetes and other Kubernetes-enabled platforms by providing the essential features you need to keep your PostgreSQL clusters up and running, including:
    \- PostgreSQL Cluster Provisioning
    \- High-Availability
    \- Disaster Recovery
    \- Monitoring
    \- PostgreSQL User Management
    \- Upgrade Management
    \- Advanced Replication Support
    \- Clone
    \- Connection Pooling
    \- Node Affinity
    \- Scheduled Backups
    \- Multi-Namespace Support

.PP
and more.


.SH USAGE
.PP
For more information on the PostgreSQL Operator, see the official PostgreSQL Operator Documentation: https://access.crunchydata.com/documentation/postgres-operator/


.SH LABELS
.PP
The starter container includes the following LABEL settings:

.PP
That atomic command runs the Docker command set in this label:

.PP
\fB\fCName=\fR

.PP
The registry location and name of the image. For example, Name="registry.developers.crunchydata.com/crunchydata/postgres-operator".

.PP
\fB\fCVersion=\fR

.PP
The Red Hat Enterprise Linux version from which the container was built. For example, Version="7.7"

.PP
\fB\fCRelease=\fR

.PP
The specific release number of the container. For example, Release="4.5.0"
