kind: Component
images:
- name: image-pgadmin
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4
  newTag: ubi9-9.17-2633
- name: image-pgbackrest
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest
  newTag: ubi9-2.59.0-2633
- name: image-pgbouncer
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer
  newTag: ubi9-1.25-2633
- name: image-postgres-exporter
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter
  newTag: ubi9-0.19.1-2633
- name: image-postgres-operator-6.0
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi9-6.0.3-0
- name: image-postgres-operator-5.8
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi9-5.8.9-0
- name: image-crunchy-postgres-15
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-15.19-2633
- name: image-crunchy-postgres-16
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-16.15-2633
- name: image-crunchy-postgres-17
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-17.11-2633
- name: image-crunchy-postgres-18
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi9-18.6-2633
- name: image-crunchy-upgrade
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade
  newTag: ubi9-18.6-2633
- name: image-crunchy-postgres-15-gis-3.3
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-15.19-3.3-2633
- name: image-crunchy-postgres-15-gis-3.4
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-15.19-3.4-2633
- name: image-crunchy-postgres-16-gis-3.3
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-16.15-3.3-2633
- name: image-crunchy-postgres-16-gis-3.4
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-16.15-3.4-2633
- name: image-crunchy-postgres-17-gis-3.4
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.11-3.4-2633
- name: image-crunchy-postgres-17-gis-3.5
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.11-3.5-2633
- name: image-crunchy-postgres-17-gis-3.6
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-17.11-3.6-2633
- name: image-crunchy-postgres-18-gis-3.6
  newName: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi9-18.6-3.6-2633
