FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
	Release="3.2.0" \
	summary="crunchy data's postgres operator backrest" \
	description="crunchy data postgres operator backrest"

RUN yum -y update && yum -y clean all


RUN mkdir -p /opt/cpm/bin && chown -R 26:26 /opt/cpm
ADD bin/pgo-backrest/ /opt/cpm/bin

USER 26
CMD ["/opt/cpm/bin/pgo-backrest"]
