ARG RELVER
FROM centos:7

MAINTAINER info@crunchydata.com

LABEL Vendor="Crunchy Data Solutions" \
	PostgresVersion="12" \
	PostgresFullVersion="12.1" \
	Version="7.7" \
	Release="${RELVER}" \
	org.opencontainers.image.vendor="Crunchy Data Solutions" \
	postgresql.version.major="12" \
	postgresql.version="12.1" \
	os.version="7.7"

COPY redhat/licenses /licenses
COPY licenses /licenses

RUN yum -y update && yum -y clean all
