ARG RELVER
FROM centos:7

MAINTAINER info@crunchydata.com

LABEL Vendor="Crunchy Data Solutions" \
	PostgresVersion="11" \
	PostgresFullVersion="11.5" \
	Version="7.7" \
	Release="${RELVER}" \
	org.opencontainers.image.vendor="Crunchy Data Solutions" \
	postgresql.version.major="11" \
	postgresql.version="11.5" \
	os.version="7.7"

COPY redhat/licenses /licenses
COPY licenses /licenses

RUN yum -y update && yum -y clean all

