FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
	PostgresVersion="11" \
	PostgresFullVersion="11.5" \
	Version="7.7" \
	Release="4.1.0" \
	summary="Crunchy Data PostgreSQL Operator - pgo-event" \
	description="Crunchy Data PostgreSQL Operator - pgo-event"

RUN yum -y update && yum -y clean all

COPY redhat/licenses /licenses
COPY licenses /licenses

ADD bin/pgo-event /usr/local/bin

USER daemon

ENTRYPOINT ["/usr/local/bin/pgo-event.sh"]
