FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
	Version="7.7" \
	Release="4.1.2" \
	summary="Crunchy Data PostgreSQL Operator - Remove Data" \
	description="Crunchy Data PostgreSQL Operator - Remove Data"

RUN yum -y update && yum -y clean all

COPY redhat/licenses /licenses
COPY licenses /licenses

ADD bin/pgo-rmdata/ /usr/local/bin

USER 0

CMD ["/usr/local/bin/start.sh"]
