ARG PREFIX
ARG BASEVER
FROM ${PREFIX}/pgo-base:centos7-${BASEVER}

LABEL summary="Crunchy Data PostgreSQL Operator - Display PVC" \
	description="Crunchy Data PostgreSQL Operator - Display contents of a PVC"

VOLUME ["/pgdata"]

USER 26

CMD ["sh", "-c", "find /pgdata/${BACKUP_ROOT}"]
