ARG BASEOS
ARG BASEVER
ARG PREFIX
FROM ${PREFIX}/pgo-base:${BASEOS}-${BASEVER}

LABEL name="postgres-operator" \
	summary="Crunchy PostgreSQL Operator" \
	description="Crunchy PostgreSQL Operator"

ENV PGVERSION="12"

RUN yum -y install hostname postgresql12  && yum -y clean all

ADD bin/postgres-operator /usr/local/bin
ADD conf/postgres-operator /default-pgo-config

USER daemon

ENTRYPOINT ["postgres-operator"]
