FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
	PostgresVersion="10" \
	PostgresFullVersion="10.5" \
	Version="7.5" \
	Release="3.2.0" \
	summary="Crunchy Data PostgreSQL Operator - pgBackRest" \
	description="pgBackRest image that is integrated for use with Crunchy Data's PostgreSQL Operator."

RUN yum -y update && yum -y clean all

RUN mkdir -p /opt/cpm/bin && chown -R 26:26 /opt/cpm
ADD bin/pgo-backrest/ /opt/cpm/bin

USER 26
CMD ["/opt/cpm/bin/pgo-backrest"]
