FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
	PostgresVersion="12" \
	PostgresFullVersion="12.1" \
	Version="7.7" \
	Release="4.1.2" \
	summary="Crunchy Data PostgreSQL Operator - pgo-event" \
	description="Crunchy Data PostgreSQL Operator - pgo-event"

RUN yum -y update && yum -y clean all

COPY redhat/licenses /licenses
COPY licenses /licenses

ADD bin/pgo-event /usr/local/bin

USER daemon

ENTRYPOINT ["/usr/local/bin/pgo-event.sh"]
