FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
	Version="7.5" \
	Release="3.2.0" \
	summary="Crunchy Data PostgreSQL Operator - Remove Data" \
	description="Crunchy Data PostgreSQL Operator - Remove Data"

RUN yum -y update && yum -y clean all

VOLUME ["/pgdata"]

USER 26

CMD ["sh", "-xc", "rm -rf /pgdata/${DATA_ROOT}"]
