ARG PREFIX
ARG BASEVER
FROM ${PREFIX}/pgo-base:centos7-${BASEVER}

LABEL name="pgo-event" \
	summary="Crunchy PostgreSQL Operator - pgo-event" \
	description="Crunchy PostgreSQL Operator - pgo-event"

ADD bin/pgo-event /usr/local/bin

USER daemon

ENTRYPOINT ["/usr/local/bin/pgo-event.sh"]
