FROM centos:7

LABEL Release="1.2.9" Vendor="Crunchy Data Solutions" 

RUN yum -y install bind-utils \
	hostname \
	openssh-clients \
 	procps-ng   && yum -y clean all

ADD bin/crunchy-operator /usr/local/bin

VOLUME ["/pgconf"]

USER daemon

ENTRYPOINT ["crunchy-operator"]
