FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
	Version="7.5" \
	Release="3.2.0" \
	summary="Crunchy Data PostgreSQL Operator - Display PVC" \
	description="Crunchy Data PostgreSQL Operator - Display contents of a PVC"

RUN yum -y update && yum -y clean all

VOLUME ["/pgdata"]

USER 26

CMD ["sh", "-c", "ls /pgdata/${BACKUP_ROOT}"]
