ARG BASEOS
ARG BASEVER
ARG PREFIX
ARG PGVERSION
ARG BACKREST_VERSION
FROM ${PREFIX}/pgo-base:${BASEOS}-${BASEVER}

LABEL name="postgres-operator" \
	summary="Crunchy PostgreSQL Operator" \
	description="Crunchy PostgreSQL Operator"

RUN yum -y install hostname postgresql${PGVERSION}  && yum -y clean all

ADD bin/postgres-operator /usr/local/bin
ADD conf/postgres-operator /default-pgo-config

USER 2

ENTRYPOINT ["postgres-operator"]
