= postgres Operator User Guide
v1.1.0, {docdate}

This document is meant for users and demonstrates
the basic interface of the *pgo* command line interface.

== Create Cluster

To create a database, use the following:
....
pgo create cluster mycluster
....

You can then view that database as:
....
pgo show cluster mydatabase
....

The output will give you the current status of the database pod
and the IP address of the database service.  If you have *postgresql*
installed on your test system you can connect to the
database using the service IP address:
....
psql -h 10.105.121.12 -U postgres postgres
....

You can view *all* databases using the special keyword *all*:
....
pgo show cluster all
....

You can filter the results based on the Postgres Version:
....
pgo show cluster all --version=9.6.2
....

== Backup Cluster

You can start a backup job for a cluster as follows:
....
pgo backup mycluster
....

You can view the backup:
....
pgo show backup mycluster
....

You can view the backup along with a PVC listing:
....
pgo show backup mycluster --show-pvc=true
....

The output of the backup will list the backup snapshots
found in the backup PVC, for example:
....
backup job pods for cluster mycluster...
└── backup-mycluster-63fw1
└── mydatabase

database pod mycluster is found

├── mycluster-backups/2017-03-27-13-54-33
├── mycluster-backups/2017-03-27-13-56-49
└── mycluster-backups/2017-03-27-14-02-38
....

This output is important in that it can let you copy/paste
a backup snapshot path and use it for restoring a database or
essentially cloning a database with an existing backup archive.

For example, to restore a database from a backup archive:
....
pgo create cluster restoredb --backup-path=mycluster-backups/2017-03-27-13-56-49 --backup-pvc=crunchy-pvc
....

This will create a new database called *restoredb* based on the
backup found in *mycluster-backups/2017-03-27-13-56-49*.


== Cluster Removal

You can remove a cluster by running:
....
pgo delete cluster restoredb
....

Note, that this command will not remove the PVC associated with
this cluster.  If you want to remove the cluster's old data files,
you will need to remove it manually.

== Cluster Replication

When you create a Cluster, you will see in the output a variety of Kubernetes objects were created including:

 * a Deployment holding the master PostgreSQL database
 * a Deployment holding the replica PostgreSQL database
 * a service for the master database
 * a service for the replica databases

Since Postgres is a single-master database by design, the master
Deployment is set to a replica count of 1, it can not scale beyond 1.

The replica Deployment is set to an initial value of 2, you will
see there are 2 replica databases running.  Those replica databases
are in read-only mode, but you can scale up the number of replicas
beyond 2 if you need higher read scaling.

There are 2 connections available to the postgres cluster, one is
to the master database which allows read-write SQL processing, and
the other is to the set of read-only replica databases.  The replica
service performs round-robin load balancing to the 2 replica databases.

You can connect to the master database and verify that it is replicating
to the 2 replica databases as follows:
....
psql -h 10.107.180.159 -U postgres postgres -c 'table pg_stat_replication'
....

You can view *all* clusters using the special keyword *all*:
....
pgo show cluster all
....

You can filter the results by Postgres version:
....
pgo show cluster all --version=9.6.2
....


== Minor Cluster Upgrade

You can perform a minor Postgres version upgrade
of either a database or cluster as follows:
....
pgo create upgrade mycluster
....

When you run this command, it will cause the operator
to delete the existing containers of the database or cluster
and recreate them using the currently defined Postgres
container image specified in your pgo configuration file.

The database data files remain untouched, only the container
is updated, this will upgrade your Postgres server version only.

== Major Cluster Upgrade

You can perform a major Postgres version upgrade
of either a database or cluster as follows:
....
pgo create upgrade mycluster --upgrade-type=major
....

When you run this command, it will cause the operator
to delete the existing containers of the database or cluster
and recreate them using the currently defined Postgres
container image specified in your pgo configuration file.

The database data files are converted to the new major Postgres
version as specified by the current Postgres image version
in your pgo configuration file.  Currently only a Postgres
9.5 to 9.6 upgrade is supported.

In this scenario, the upgrade is performed by the Postgres
pg_upgrade utility which is containerized in the *crunchydata/crunchy-upgrade*
container.  The operator will create a Job which runs the upgrade container,
using the existing Postgres database files as input, and output
the updated database files to a new PVC.

Once the upgrade job is completed, the operator will create the
original database or cluster container mounted with the new PVC
which contains the upgraded database files.

As the upgrade is processed, the status of the *pgupgrade* TPR is
updated to give the user some insight into how the upgrade is
proceeding.  Upgrades like this can take a long time if your
database is large.  The operator creates a watch on the upgrade
job to know when and how to proceed.

== Viewing PVC Information

You can view the files on a PVC as follows:
....
pgo show pvc crunchy-pvc
....

In this example, the PVC is *crunchy-pvc*.  This command is useful
in some cases to examine what files are on a given PVC.

== Viewing Passwords

You can view the passwords used by the cluster as follows:
....
pgo show cluster mycluster --show-secrets=true
....

Passwords are generated if not specified in your *pgo* configuration.
